/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGoalTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal-templates/{goalTemplateId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedGoalGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedKnowledgeNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedPrerequisites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedDependents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/knowledge/versions/{versionId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateKnowledgeGraphVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/knowledge/versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishKnowledgeGraphVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CsrfResponse: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            timezone: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ProfileResponse: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            timezone: string;
            /** Format: int64 */
            version: number;
        };
        GoalTemplateResponse: {
            id: string;
            key: string;
            displayName: string;
            description: string;
        };
        CreateGoalRequest: {
            goalTemplateId: string;
            /** Format: date */
            targetDate: string;
            timezone: string;
            defaultDailyMinutes: number;
        };
        GoalResponse: {
            id: string;
            goalTemplateId: string;
            /** Format: date */
            targetDate: string;
            timezone: string;
            defaultDailyMinutes: number;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "CANCELLED";
            /** Format: int64 */
            version: number;
        };
        KnowledgeNodeResponse: {
            id: string;
            graphVersionId: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: number;
            estimatedMinutes: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "DEPRECATED" | "ARCHIVED";
        };
        GoalGraphNode: {
            id: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: number;
            estimatedMinutes: number;
            status: string;
            relevanceWeight: number;
            requiredMastery: number;
            terminal: boolean;
        };
        KnowledgeEdge: {
            id: string;
            sourceNodeId: string;
            targetNodeId: string;
            /** @enum {string} */
            type: "PREREQUISITE" | "PART_OF" | "RELATED" | "APPLIED_IN";
            strength: number;
            /** @enum {string} */
            status: "ACTIVE" | "DEPRECATED";
            rationale: string;
        };
        GoalGraphResponse: {
            graphVersionId: string;
            curriculumKey: string;
            versionLabel: string;
            /** Format: date-time */
            publishedAt: string;
            nodes: components["schemas"]["GoalGraphNode"][];
            edges: components["schemas"]["KnowledgeEdge"][];
            truncated: boolean;
            nextCursor?: string | null;
        };
        GraphViolation: {
            code: string;
            detail: string;
            nodePath: string[];
        };
        GraphValidationResponse: {
            graphVersionId: string;
            /** @enum {string} */
            status: "DRAFT" | "VALIDATED";
            valid: boolean;
            transitioned: boolean;
            violations: components["schemas"]["GraphViolation"][];
        };
        GraphPublicationResponse: {
            graphVersionId: string;
            curriculumKey: string;
            versionLabel: string;
            /** @enum {string} */
            status: "PUBLISHED";
            /** Format: date-time */
            publishedAt: string;
            replayed: boolean;
        };
        FieldError: {
            field: string;
            code: string;
        };
        ApiProblem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            instance: string;
            correlationId: string;
            fieldErrors: components["schemas"]["FieldError"][];
        };
    };
    responses: {
        /** @description Request failed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: {
        CsrfHeader: string;
        GoalTemplateId: string;
        NodeId: string;
        VersionId: string;
        Transitive: boolean;
        GraphLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token metadata for the browser client. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and session authenticated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current learner profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listGoalTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active goal templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalTemplateResponse"][];
                };
            };
        };
    };
    getPublishedGoalGraph: {
        parameters: {
            query?: {
                anchorNodeId?: string;
                depth?: number;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                goalTemplateId: components["parameters"]["GoalTemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current published graph for the active goal template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalGraphResponse"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getPublishedKnowledgeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A node in a published graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPublishedPrerequisites: {
        parameters: {
            query?: {
                transitive?: components["parameters"]["Transitive"];
                limit?: components["parameters"]["GraphLimit"];
            };
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable direct or transitive prerequisite nodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"][];
                };
            };
        };
    };
    getPublishedDependents: {
        parameters: {
            query?: {
                transitive?: components["parameters"]["Transitive"];
                limit?: components["parameters"]["GraphLimit"];
            };
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable direct or transitive dependent nodes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"][];
                };
            };
        };
    };
    validateKnowledgeGraphVersion: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic validation result; invalid drafts remain drafts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphValidationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    publishKnowledgeGraphVersion: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version published atomically, or replay of the current publication. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPublicationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            /** @description Original result replayed for the same idempotency key and request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Goal created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getActiveGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current active goal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
