/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGoalTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goal-templates/{goalTemplateId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedGoalGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedKnowledgeNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedPrerequisites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/nodes/{nodeId}/dependents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedDependents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/knowledge/versions/{versionId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateKnowledgeGraphVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/knowledge/versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishKnowledgeGraphVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveGoal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startDiagnostic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{sessionId}/next-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNextDiagnosticQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{sessionId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitDiagnosticAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{sessionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDiagnosticResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyKnowledgeState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/me/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyKnowledgeState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/me/{nodeId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyKnowledgeEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDueReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/progress/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuildProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLearningSequences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/sequences/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLearningSequence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/sequences/{key}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startLearningSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveLearningSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLearningSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["blockLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/tasks/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abandonLearningTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LearningSequenceStep: {
            position: number;
            /** @enum {string} */
            activityType: "LEARN" | "PRACTICE" | "RECALL";
            minutes: number;
            title: string;
        };
        LearningSequenceResponse: {
            key: string;
            version: number;
            graphVersionId: string;
            title: string;
            description: string;
            totalMinutes: number;
            steps: components["schemas"]["LearningSequenceStep"][];
        };
        LearningChecklistStep: {
            id: string;
            label: string;
        };
        LearningTaskResponse: {
            id: string;
            position: number;
            /** @enum {string} */
            status: "ASSIGNED" | "IN_PROGRESS" | "BLOCKED" | "COMPLETED" | "SKIPPED" | "ABANDONED" | "EXPIRED";
            /** @enum {string} */
            activityType: "LEARN" | "PRACTICE" | "RECALL";
            /** @enum {string} */
            evaluationMode: "NONE" | "SELF_REPORT";
            plannedMinutes: number;
            actualMinutes?: number | null;
            title: string;
            instructions: string;
            resourceTitle: string;
            resourceBody: string;
            checklist: components["schemas"]["LearningChecklistStep"][];
        };
        LearningSessionResponse: {
            id: string;
            sequenceKey: string;
            title: string;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "STOPPED";
            graphVersionId: string;
            /** @enum {string} */
            assignmentSource: "LEARNER_SELECTED" | "PLANNER";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            tasks: components["schemas"]["LearningTaskResponse"][];
        };
        LearningStartResponse: {
            sessionId: string;
            replayed: boolean;
        };
        LearningCommandResponse: {
            taskId: string;
            status: string;
            replayed: boolean;
        };
        LearningCompleteRequest: {
            actualMinutes: number;
            completedStepIds: string[];
        };
        LearningReasonRequest: {
            /** @enum {string} */
            reasonCode: "TIME" | "DIFFICULT" | "OTHER";
        };
        CsrfResponse: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            timezone: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ProfileResponse: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            timezone: string;
            /** Format: int64 */
            version: number;
        };
        GoalTemplateResponse: {
            id: string;
            key: string;
            displayName: string;
            description: string;
        };
        CreateGoalRequest: {
            goalTemplateId: string;
            /** Format: date */
            targetDate: string;
            timezone: string;
            defaultDailyMinutes: number;
        };
        GoalResponse: {
            id: string;
            goalTemplateId: string;
            /** Format: date */
            targetDate: string;
            timezone: string;
            defaultDailyMinutes: number;
            /** @enum {string} */
            status: "ACTIVE" | "COMPLETED" | "CANCELLED";
            /** Format: int64 */
            version: number;
        };
        KnowledgeNodeResponse: {
            id: string;
            graphVersionId: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: number;
            estimatedMinutes: number;
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "DEPRECATED" | "ARCHIVED";
        };
        GoalGraphNode: {
            id: string;
            slug: string;
            name: string;
            description: string;
            category: string;
            difficulty: number;
            estimatedMinutes: number;
            status: string;
            relevanceWeight: number;
            requiredMastery: number;
            terminal: boolean;
        };
        KnowledgeEdge: {
            id: string;
            sourceNodeId: string;
            targetNodeId: string;
            /** @enum {string} */
            type: "PREREQUISITE" | "PART_OF" | "RELATED" | "APPLIED_IN";
            strength: number;
            /** @enum {string} */
            status: "ACTIVE" | "DEPRECATED";
            rationale: string;
        };
        GoalGraphResponse: {
            graphVersionId: string;
            curriculumKey: string;
            versionLabel: string;
            /** Format: date-time */
            publishedAt: string;
            nodes: components["schemas"]["GoalGraphNode"][];
            edges: components["schemas"]["KnowledgeEdge"][];
            truncated: boolean;
            nextCursor?: string | null;
        };
        GraphViolation: {
            code: string;
            detail: string;
            nodePath: string[];
        };
        GraphValidationResponse: {
            graphVersionId: string;
            /** @enum {string} */
            status: "DRAFT" | "VALIDATED";
            valid: boolean;
            transitioned: boolean;
            violations: components["schemas"]["GraphViolation"][];
        };
        GraphPublicationResponse: {
            graphVersionId: string;
            curriculumKey: string;
            versionLabel: string;
            /** @enum {string} */
            status: "PUBLISHED";
            /** Format: date-time */
            publishedAt: string;
            replayed: boolean;
        };
        AssessmentSessionResponse: {
            id: string;
            goalId: string;
            graphVersionId: string;
            assessmentPolicyVersion: string;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED" | "EXPIRED";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            answeredQuestions: number;
            totalQuestions: number;
            created: boolean;
            resumed: boolean;
        };
        AssessmentQuestionOption: {
            id: string;
            label: string;
        };
        AssessmentQuestionResponse: {
            sessionId: string;
            sessionQuestionId: string;
            questionVersionId: string;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE";
            prompt: string;
            difficulty: number;
            estimatedSeconds: number;
            position: number;
            totalQuestions: number;
            /** Format: date-time */
            expiresAt: string;
            options: components["schemas"]["AssessmentQuestionOption"][];
        };
        SubmitAssessmentAttemptRequest: {
            sessionQuestionId: string;
            selectedOptionIds: string[];
            selfConfidence?: number | null;
            timeSpentSeconds: number;
        };
        AssessmentAttemptResponse: {
            attemptId: string;
            /** @enum {string} */
            sessionStatus: "IN_PROGRESS" | "COMPLETED" | "EXPIRED";
            replayed: boolean;
        };
        /** @description Observational evidence from one evaluated attempt; not authoritative mastery. */
        AssessmentEvidenceResponse: {
            evidenceId: string;
            attemptId: string;
            knowledgeNodeId: string;
            knowledgeNodeSlug: string;
            knowledgeNodeName: string;
            /** @enum {string} */
            dimension: "RECOGNITION" | "UNDERSTANDING";
            score: number;
            reliability: number;
            evaluatorVersion: string;
            /** Format: date-time */
            observedAt: string;
        };
        AssessmentResultResponse: {
            sessionId: string;
            graphVersionId: string;
            assessmentPolicyVersion: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            answeredQuestions: number;
            totalQuestions: number;
            overallObjectiveScore: number;
            evidence: components["schemas"]["AssessmentEvidenceResponse"][];
            interpretation: string;
        };
        FieldError: {
            field: string;
            code: string;
        };
        ApiProblem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            instance: string;
            correlationId: string;
            fieldErrors: components["schemas"]["FieldError"][];
        };
        KnowledgeStateResponse: {
            knowledgeNodeId: string;
            knowledgeNodeSlug: string;
            knowledgeNodeName: string;
            graphVersionId: string;
            recognition: number;
            understanding: number;
            recall: number;
            application: number;
            storedMastery: number;
            effectiveMastery: number;
            confidence: number;
            evidenceCount: number;
            /** Format: date-time */
            lastEvidenceAt?: string;
            /** Format: date-time */
            nextReviewAt?: string;
            /** @enum {string} */
            status: "UNKNOWN" | "LEARNING" | "PROVISIONAL" | "MASTERED" | "REVIEW_DUE";
            policyVersion: string;
        };
        KnowledgeStatePageResponse: {
            items: components["schemas"]["KnowledgeStateResponse"][];
            hasMore: boolean;
            nextCursor?: string;
        };
        KnowledgeEvidenceResponse: {
            evidenceId: string;
            sourceType: string;
            sourceId: string;
            /** @enum {string} */
            dimension: "RECOGNITION" | "UNDERSTANDING" | "RECALL" | "APPLICATION";
            score: number;
            reliability: number;
            policyVersion: string;
            /** Format: date-time */
            observedAt: string;
        };
        KnowledgeEvidencePageResponse: {
            items: components["schemas"]["KnowledgeEvidenceResponse"][];
            hasMore: boolean;
            nextCursor?: string;
        };
        ReviewResponse: {
            reviewScheduleId: string;
            knowledgeNodeId: string;
            knowledgeNodeSlug: string;
            knowledgeNodeName: string;
            intervalIndex: number;
            /** Format: date-time */
            dueAt: string;
            policyVersion: string;
        };
        ReviewPageResponse: {
            items: components["schemas"]["ReviewResponse"][];
            hasMore: boolean;
            nextCursor?: string;
        };
        ProgressRebuildResponse: {
            /** @enum {string} */
            status: "COMPLETED";
            projectedNodes: number;
        };
    };
    responses: {
        /** @description Request failed. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: {
        /** @description Preferred learner presentation language. Unsupported values fall back to English. */
        AcceptLanguage: "vi-VN" | "en";
        CsrfHeader: string;
        IdempotencyHeader: string;
        GoalTemplateId: string;
        NodeId: string;
        VersionId: string;
        AssessmentSessionId: string;
        Transitive: boolean;
        GraphLimit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Resolved language used for localized learner content. */
        ContentLanguage: "vi-VN" | "en";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token metadata for the browser client. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and session authenticated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current learner profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listGoalTemplates: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active goal templates. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalTemplateResponse"][];
                };
            };
        };
    };
    getPublishedGoalGraph: {
        parameters: {
            query?: {
                anchorNodeId?: string;
                depth?: number;
                limit?: number;
                cursor?: string;
            };
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                goalTemplateId: components["parameters"]["GoalTemplateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current published graph for the active goal template. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalGraphResponse"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getPublishedKnowledgeNode: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A node in a published graph. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPublishedPrerequisites: {
        parameters: {
            query?: {
                transitive?: components["parameters"]["Transitive"];
                limit?: components["parameters"]["GraphLimit"];
            };
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable direct or transitive prerequisite nodes. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"][];
                };
            };
        };
    };
    getPublishedDependents: {
        parameters: {
            query?: {
                transitive?: components["parameters"]["Transitive"];
                limit?: components["parameters"]["GraphLimit"];
            };
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable direct or transitive dependent nodes. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeResponse"][];
                };
            };
        };
    };
    validateKnowledgeGraphVersion: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic validation result; invalid drafts remain drafts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphValidationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    publishKnowledgeGraphVersion: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version published atomically, or replay of the current publication. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPublicationResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGoalRequest"];
            };
        };
        responses: {
            /** @description Original result replayed for the same idempotency key and request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Goal created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getActiveGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current active goal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    startDiagnostic: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing in-progress or completed diagnostic returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSessionResponse"];
                };
            };
            /** @description New diagnostic session created with pinned question versions. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSessionResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getNextDiagnosticQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                sessionId: components["parameters"]["AssessmentSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next pinned unanswered question. The answer key is never included. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentQuestionResponse"];
                };
            };
            /** @description Diagnostic is completed and has no next question. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    submitDiagnosticAttempt: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": string;
            };
            path: {
                sessionId: components["parameters"]["AssessmentSessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAssessmentAttemptRequest"];
            };
        };
        responses: {
            /** @description Original accepted attempt replayed for the same key and payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAttemptResponse"];
                };
            };
            /** @description Attempt, concept evidence, and durable handoff created atomically. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAttemptResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getDiagnosticResult: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                sessionId: components["parameters"]["AssessmentSessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observational concept evidence, not authoritative mastery or a recommendation. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResultResponse"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listMyKnowledgeState: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Learner-owned effective knowledge-state page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStatePageResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getMyKnowledgeState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Learner-owned knowledge state for one concept. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStateResponse"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listMyKnowledgeEvidence: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only evidence provenance page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeEvidencePageResponse"];
                };
            };
        };
    };
    listDueReviews: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews due at the server clock for the current learner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPageResponse"];
                };
            };
        };
    };
    rebuildProgress: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic replay completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRebuildResponse"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    listLearningSequences: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active compatible learner-selected sequences; never a personalized plan. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSequenceResponse"][];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getLearningSequence: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded sequence description. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSequenceResponse"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    startLearningSession: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing or replayed active session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningStartResponse"];
                };
            };
            /** @description New learner-selected session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningStartResponse"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getActiveLearningSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current study session from pinned task snapshots. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionResponse"];
                };
            };
            /** @description No active learner-selected session. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
        };
    };
    getLearningSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Preferred learner presentation language. Unsupported values fall back to English. */
                "Accept-Language"?: components["parameters"]["AcceptLanguage"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owned active or historical study session. */
            200: {
                headers: {
                    "Content-Language": components["headers"]["ContentLanguage"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionResponse"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    startLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task started or replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    completeLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningCompleteRequest"];
            };
        };
        responses: {
            /** @description Engagement-only completion or replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    skipLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningReasonRequest"];
            };
        };
        responses: {
            /** @description Task skipped and session stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    blockLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningReasonRequest"];
            };
        };
        responses: {
            /** @description Task blocked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    resumeLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocked task resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    abandonLearningTask: {
        parameters: {
            query?: never;
            header: {
                "X-XSRF-TOKEN": components["parameters"]["CsrfHeader"];
                "Idempotency-Key": components["parameters"]["IdempotencyHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningReasonRequest"];
            };
        };
        responses: {
            /** @description Task abandoned and session stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningCommandResponse"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
}
